export const USER_PROJECT_REQUESTED = "USER_PROJECT_REQUESTED"
export const USER_PROJECT_SUCCEEDED = "USER_PROJECT_SUCCEEDED"
export const USER_PROJECT_FAILURE = "USER_PROJECT_FAILURE"

export const USER_ADD_PROJECT_REQUESTED = 'USER_ADD_PROJECT_REQUESTED'
export const USER_ADD_PROJECT_SUCCEEDED = 'USER_ADD_PROJECT_SUCCEEDED'
export const USER_ADD_PROJECT_FAILURE = 'USER_ADD_PROJECT_FAILURE'
