export const USER_TASK_REQUESTED = "USER_TASK_REQUESTED"
export const USER_TASK_SUCCEEDED = "USER_TASK_SUCCEEDED"
export const USER_TASK_FAILURE = "USER_TASK_FAILURE"

export const USER_ADD_TASK_REQUESTED='USER_ADD_TASK_REQUESTED'
export const USER_ADD_TASK_SUCCEEDED='USER_ADD_TASK_SUCCEEDED'
export const USER_ADD_TASK_FAILURE='USER_ADD_TASK_FAILURE'